#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
config["wghost"] = os.getenv("WG_HOST","")
config["password"] = os.getenv("PASSWORD","")
config["allowedips"] = os.getenv("WG_ALLOWED_IPS","0.0.0.0/24")
config["dns"] = os.getenv("WG_DEFAULT_DNS","1.1.1.1")
config["mtu"] = os.getenv("MTU","1420")
config["wgmtu"] = os.getenv("WG_MTU","1420")

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
